// src/components/UpdateDialog.tsx
/**
 * UpdateDialog Component - React version
 *
 * Dialog for displaying update status and download progress.
 */
import { useTranslation } from 'react-i18next';
import {
  Download,
  RefreshCw,
  AlertCircle,
  CheckCircle2,
  Loader2,
  Power,
} from 'lucide-react';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import type { UpdateAvailablePayload } from '@/hooks/useUpdater';

export interface UpdateDialogProps {
  open: boolean;
  updateInfo: UpdateAvailablePayload | null;
  downloadProgress: number;
  downloadedBytes: number;
  totalBytes: number;
  isDownloading: boolean;
  isInstalling: boolean;
  updateError: string | null;
  isReadyToRestart: boolean;
  onClose: () => void;
  onDownload: () => void;
  onRestart: () => void;
}

export function UpdateDialog({
  open,
  updateInfo,
  downloadProgress,
  downloadedBytes,
  isDownloading,
  isInstalling,
  updateError,
  isReadyToRestart,
  onClose,
  onDownload,
  onRestart,
}: UpdateDialogProps) {
  const { t } = useTranslation();

  return (
    <AlertDialog open={open} onOpenChange={(v) => !v && onClose()}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle className="flex items-center gap-2">
            <RefreshCw className="w-5 h-5" />
            {t('updater.title')}
          </AlertDialogTitle>
          <AlertDialogDescription>
            {/* Ready to restart */}
            {isReadyToRestart && (
              <div className="space-y-3">
                <p className="flex items-center gap-2 text-green-600">
                  <CheckCircle2 className="w-4 h-4" />
                  {t('updater.readyToRestart')}
                </p>
                <p className="text-sm text-muted-foreground">
                  {t('updater.restartNowOrLater')}
                </p>
              </div>
            )}

            {/* Update Available */}
            {updateInfo && !isDownloading && !isInstalling && !updateError && !isReadyToRestart && (
              <div className="space-y-3">
                <p>{t('updater.newVersionAvailable')}</p>
                <div className="flex items-center justify-center gap-4 py-2">
                  <span className="text-muted-foreground">
                    {t('updater.currentVersion')}:
                  </span>
                  <span className="font-medium">v{updateInfo.current_version}</span>
                  <span className="text-muted-foreground">→</span>
                  <span className="font-medium text-green-600">
                    v{updateInfo.version}
                  </span>
                </div>
              </div>
            )}

            {/* Downloading */}
            {isDownloading && !isInstalling && (
              <div className="space-y-3">
                <p className="flex items-center gap-2">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  {t('updater.downloading')}
                </p>
                <Progress value={downloadProgress} className="w-full" />
                <p className="text-sm text-muted-foreground text-center">
                  {downloadProgress > 0
                    ? `${downloadProgress}%`
                    : `${(downloadedBytes / 1024 / 1024).toFixed(1)} MB`}
                </p>
              </div>
            )}

            {/* Installing */}
            {isInstalling && (
              <div className="space-y-3">
                <p className="flex items-center gap-2 text-green-600">
                  <CheckCircle2 className="w-4 h-4" />
                  {t('updater.downloadComplete')}
                </p>
                <p className="text-sm text-muted-foreground">
                  {t('updater.installing')}
                </p>
              </div>
            )}

            {/* Error */}
            {updateError && (
              <div className="space-y-3">
                <p className="flex items-center gap-2 text-red-600">
                  <AlertCircle className="w-4 h-4" />
                  {t('updater.updateFailed')}
                </p>
                <p className="text-sm text-muted-foreground">{updateError}</p>
              </div>
            )}
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter className="flex gap-2">
          {/* Ready to restart */}
          {isReadyToRestart && (
            <>
              <Button variant="outline" onClick={onClose}>
                {t('updater.later')}
              </Button>
              <AlertDialogAction onClick={onRestart}>
                <Power className="w-4 h-4 mr-2" />
                {t('updater.restartNow')}
              </AlertDialogAction>
            </>
          )}

          {/* Update available */}
          {updateInfo && !isDownloading && !isInstalling && !updateError && !isReadyToRestart && (
            <>
              <Button variant="outline" onClick={onClose}>
                {t('updater.later')}
              </Button>
              <AlertDialogAction onClick={onDownload}>
                <Download className="w-4 h-4 mr-2" />
                {t('updater.downloadNow')}
              </AlertDialogAction>
            </>
          )}

          {/* Downloading */}
          {isDownloading && !isInstalling && (
            <Button variant="outline" disabled>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              {t('updater.downloading')}...
            </Button>
          )}

          {/* Installing */}
          {isInstalling && (
            <Button variant="outline" disabled>
              {t('updater.installing')}...
            </Button>
          )}

          {/* Error */}
          {updateError && (
            <>
              <Button variant="outline" onClick={onClose}>
                {t('updater.close')}
              </Button>
              <AlertDialogAction onClick={onDownload}>
                {t('updater.retry')}
              </AlertDialogAction>
            </>
          )}
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}

export default UpdateDialog;

// src/components/UpdateDialog.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Progress } from '@/components/ui/progress';
import Button from '@/components/ui/button/Button.vue';
import {
  Download,
  RefreshCw,
  AlertCircle,
  CheckCircle2,
  Loader2,
  Power,
} from 'lucide-vue-next';
import type { UpdateAvailablePayload } from '@/composables/useUpdater';

defineProps<{
  open: boolean;
  updateInfo: UpdateAvailablePayload | null;
  downloadProgress: number;
  downloadedBytes: number;
  totalBytes: number;
  isDownloading: boolean;
  isInstalling: boolean;
  updateError: string | null;
  isReadyToRestart: boolean;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'download'): void;
  (e: 'restart'): void;
}>();

const { t } = useI18n();

const handleClose = () => {
  emit('close');
};

const handleDownload = () => {
  emit('download');
};

const handleRestart = () => {
  emit('restart');
};
</script>

<template>
  <AlertDialog :open="open" @update:open="handleClose">
    <AlertDialogContent>
      <AlertDialogHeader>
        <AlertDialogTitle class="flex items-center gap-2">
          <RefreshCw class="w-5 h-5" />
          {{ t('updater.title') }}
        </AlertDialogTitle>
        <AlertDialogDescription>
          <!-- Ready to restart -->
          <div v-if="isReadyToRestart" class="space-y-3">
            <p class="flex items-center gap-2 text-green-600">
              <CheckCircle2 class="w-4 h-4" />
              {{ t('updater.readyToRestart') }}
            </p>
            <p class="text-sm text-muted-foreground">
              {{ t('updater.restartNowOrLater') }}
            </p>
          </div>

          <!-- Update Available (waiting for user action) -->
          <div
            v-if="updateInfo && !isDownloading && !isInstalling && !updateError && !isReadyToRestart"
            class="space-y-3"
          >
            <p>
              {{ t('updater.newVersionAvailable') }}
            </p>
            <div class="flex items-center justify-center gap-4 py-2">
              <span class="text-muted-foreground">
                {{ t('updater.currentVersion') }}:
              </span>
              <span class="font-medium">v{{ updateInfo.current_version }}</span>
              <span class="text-muted-foreground">→</span>
              <span class="font-medium text-green-600">
                v{{ updateInfo.version }}
              </span>
            </div>
          </div>

          <!-- Downloading -->
          <div v-if="isDownloading && !isInstalling" class="space-y-3">
            <p class="flex items-center gap-2">
              <Loader2 class="w-4 h-4 animate-spin" />
              {{ t('updater.downloading') }}
            </p>
            <Progress :value="downloadProgress" class="w-full" />
            <p class="text-sm text-muted-foreground text-center">
              {{ downloadProgress > 0 ? `${downloadProgress}%` : `${(downloadedBytes / 1024 / 1024).toFixed(1)} MB` }}
            </p>
          </div>

          <!-- Installing -->
          <div v-if="isInstalling" class="space-y-3">
            <p class="flex items-center gap-2 text-green-600">
              <CheckCircle2 class="w-4 h-4" />
              {{ t('updater.downloadComplete') }}
            </p>
            <p class="text-sm text-muted-foreground">
              {{ t('updater.installing') }}
            </p>
          </div>

          <!-- Error -->
          <div v-if="updateError" class="space-y-3">
            <p class="flex items-center gap-2 text-red-600">
              <AlertCircle class="w-4 h-4" />
              {{ t('updater.updateFailed') }}
            </p>
            <p class="text-sm text-muted-foreground">
              {{ updateError }}
            </p>
          </div>
        </AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter class="flex gap-2">
        <!-- Ready to restart - show restart and later buttons -->
        <template v-if="isReadyToRestart">
          <Button variant="outline" @click="handleClose">
            {{ t('updater.later') }}
          </Button>
          <AlertDialogAction @click="handleRestart">
            <Power class="w-4 h-4 mr-2" />
            {{ t('updater.restartNow') }}
          </AlertDialogAction>
        </template>

        <!-- Update available - show download and cancel buttons -->
        <template
          v-if="updateInfo && !isDownloading && !isInstalling && !updateError && !isReadyToRestart"
        >
          <Button variant="outline" @click="handleClose">
            {{ t('updater.later') }}
          </Button>
          <AlertDialogAction @click="handleDownload">
            <Download class="w-4 h-4 mr-2" />
            {{ t('updater.downloadNow') }}
          </AlertDialogAction>
        </template>

        <!-- Downloading - show disabled close button -->
        <template v-if="isDownloading && !isInstalling">
          <Button variant="outline" disabled>
            <Loader2 class="w-4 h-4 mr-2 animate-spin" />
            {{ t('updater.downloading') }}...
          </Button>
        </template>

        <!-- Installing - show disabled button -->
        <template v-if="isInstalling">
          <Button variant="outline" disabled>
            {{ t('updater.installing') }}...
          </Button>
        </template>

        <!-- Error - show retry and close buttons -->
        <template v-if="updateError">
          <Button variant="outline" @click="handleClose">
            {{ t('updater.close') }}
          </Button>
          <AlertDialogAction @click="handleDownload">
            {{ t('updater.retry') }}
          </AlertDialogAction>
        </template>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialog>
</template>
