// src/App.tsx
import { useEffect, useState } from 'react';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { TooltipProvider } from '@/components/ui/tooltip';
import MainWindow from './features/main/pages/MainWindow';
import PopupWindow from './features/popup/pages/PopupWindow';
import ScreenshotWindow from './features/screenshot/pages/ScreenshotWindow';

type WindowType = 'main' | 'popup' | 'screenshot' | null;

export default function App() {
  const [windowType, setWindowType] = useState<WindowType>(null);

  useEffect(() => {
    const detectWindow = async () => {
      try {
        const appWindow = getCurrentWindow();
        const label = appWindow.label;

        if (label === 'main') {
          setWindowType('main');
        } else if (label === 'popup') {
          setWindowType('popup');
        } else if (label.startsWith('screenshot')) {
          setWindowType('screenshot');
        } else {
          // Default to main window
          setWindowType('main');
        }
      } catch (e) {
        console.error('Failed to get window label:', e);
        setWindowType('main');
      }
    };

    detectWindow();
  }, []);

  // Loading state
  if (windowType === null) {
    return null;
  }

  // Route to correct window component
  const renderWindow = () => {
    switch (windowType) {
      case 'main':
        return <MainWindow />;
      case 'popup':
        return <PopupWindow />;
      case 'screenshot':
        return <ScreenshotWindow />;
      default:
        return <MainWindow />;
    }
  };

  return <TooltipProvider>{renderWindow()}</TooltipProvider>;
}

// src/App.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { getCurrentWindow } from "@tauri-apps/api/window";
import MainWindow from "@/views/MainWindow.vue";
import PopupWindow from "@/views/PopupWindow.vue";
import ScreenshotWindow from "@/views/ScreenshotWindow.vue";
import ConfirmProvider from "./components/ui/alert-dialog/ConfirmProvider.vue";

const currentWindowLabel = ref("main");

onMounted(() => {
  const appWindow = getCurrentWindow();
  currentWindowLabel.value = appWindow.label;
});
</script>

<template>
  <PopupWindow v-if="currentWindowLabel === 'popup'" />
  <ScreenshotWindow v-else-if="currentWindowLabel.startsWith('screenshot')" />
  <MainWindow v-else />
  <ConfirmProvider />
</template>
